services:
  redis:
    image: redis:latest
    container_name: t_redis1
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "6379:6379"
    environment:
      - "REDIS_REPLICATION_MODE=master"

  redis1:
    image: redis:latest
    container_name: t_redis2
    command: redis-server --port 6380 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "6380:6380"
    environment:
      - "REDIS_REPLICATION_MODE=master"

  redis2:
    image: redis:latest
    container_name: t_redis3
    command: redis-server --port 6381 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "6381:6381"
    environment:
      - "REDIS_REPLICATION_MODE=master"

  swoole:
    container_name: t_swoole
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - "./app:/var/www/symfony"
    command: "tail -f /dev/null"
    user: "1000:1000"
    working_dir: "/var/www/symfony"
    ports:
      - "8080:8080"